Bug fix and refactoring - the navigation buttons should work correctly again
rBiblia/rbiblia-web pull request #17
Opened 2024-04-06 14:55 UTC by SantiagoDePolonia

2024-04-06 21:10 UTC, clash82 requested changes
Refactoring is really great here 🏆 One minor comment was added, review please.

_If you want to push something to this branch then pull it first - branch was rebased on top of latest `master`._

2024-04-06 21:10 UTC, clash82 commented on assets/js/Navigator.js
> +        <header className="container sticky-top pt-2 pb-2 user-select-none">
What's this class? Where it comes from?

2024-04-06 21:11 UTC, clash82 commented
@SantiagoDePolonia could you also check SonarCloud report? There are 9 new issues found.

2024-04-06 22:03 UTC, SantiagoDePolonia commented
Those SonarCloud issues are not new. All of them was present before. However I fixed one of them. Other are not very important and require some redundant work at this stage of the project. (Especially if you consider introducing typescript propTypes would be redundant. )

2024-04-06 22:59 UTC, clash82 commented
> Those SonarCloud issues are not new. All of them was present before. However I fixed one of them. Other are not very important and require some redundant work at this stage of the project. (Especially if you consider introducing typescript propTypes would be redundant. )

Yeah, we can skip SonarCloud recommendations for now. Could you also check my comment here https://github.com/rBiblia/rbiblia-web/pull/17#discussion_r1554714121

2024-04-07 14:00 UTC, SantiagoDePolonia commented on assets/js/Navigator.js
> +        <header className="container sticky-top pt-2 pb-2 user-select-none">
It comes from bootstrap.

2024-04-07 14:00 UTC, SantiagoDePolonia commented on assets/js/Navigator.js
> +        <header className="container sticky-top pt-2 pb-2 user-select-none">
It is css user-select:none; property

2024-04-07 14:52 UTC, clash82 commented on assets/js/Navigator.js
> +        <header className="container sticky-top pt-2 pb-2 user-select-none">
Nice, I didn't know that.

2024-04-07 14:55 UTC, clash82 approved these changes

2024-04-07 14:55 UTC, merged